site_name: radardef

theme:
  name: "material"
  logo: assets/logo.jpeg
  favicon: assets/favicon.jpeg
  features:
    - navigation.instant
    - navigation.path
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/danielk333/radardef

extra_css:
  - assets/style.css

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/scripts/generate_api_docs.py
  - literate-nav:
      nav_file: nav.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: table
            show_docstring_functions: true
            show_docstring_modules: true
            show_docstring_description: true
            inherited_members: true
            parameter_headings: true
            type_parameter_headings: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            summary: true
  - mkdocs-jupyter:
      execute: true
      include_source: true
      ignore: ["_wip*"]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Usage:
      - Install: usage/install.md
      - CLI: usage/cli.md
      - Develop/Contribute: usage/develop.md
  - Radar station: components/radar_station.md
  - Formats:
      - DRF: formats/format_drf.md
      - H5: formats/format_h5.md
      - Metadata: formats/format_meta.md
  - Reference: reference/
  - Examples:
      - Radar station: examples/radar_station.py
      - Convert data: examples/convert_data.py
      - Load data: examples/load_data.py
      - Plot sky temperature: examples/plot_sky_temperature.py
